/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ca.murillo.swigexample.jni;

public class c_source_example {
  public static void reverseBytesInPlace(byte[] inBytes, int inLen) {
    c_source_exampleJNI.reverseBytesInPlace(inBytes, inLen);
  }

  public static byte[] reverseBytesCopy(byte[] inBytes, int inLen, long[] outLen) {
    return c_source_exampleJNI.reverseBytesCopy(inBytes, inLen, outLen);
}

}
