/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ca.murillo.swigexample.jni;

public class c_source_exampleJNI {
  public final static native void reverseBytesInPlace(byte[] jarg1, int jarg2);
  public final static native byte[] reverseBytesCopy(byte[] jarg1, int jarg2, long[] jarg3);
}
